spring.main.web-application-type=none
#server.port=8050
#server.address=0.0.0.0

# Configuraci\u00c3\u00b3n Rabbit
spring.rabbitmq.host=127.0.0.1
spring.rabbitmq.port=5672
spring.rabbitmq.username=user_db
spring.rabbitmq.password=password_db

# Configuracion de Colas RabbitMQ
spring.rabbitmq.routing-key=routing.key.messages
spring.rabbitmq.exchange=exchange.messages

# Cola Entrante: Origen DB - Destino WA
spring.rabbitmq.colaDB_WA=cola.DB_WA

# Configuracion de Redis
spring.redis.host=localhost
spring.redis.port=6379
spring.redis.database=0

