// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messageOut.proto

package coop.bancocredicoop.omnited.config;

public final class MessageOut {
  private MessageOut() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MensajeJSONOrBuilder extends
      // @@protoc_insertion_point(interface_extends:coop.bancocredicoop.omnited.config.MensajeJSON)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Un campo de tipo string con el identificador único
     * </pre>
     *
     * <code>string idMensaje = 1;</code>
     * @return The idMensaje.
     */
    java.lang.String getIdMensaje();
    /**
     * <pre>
     * Un campo de tipo string con el identificador único
     * </pre>
     *
     * <code>string idMensaje = 1;</code>
     * @return The bytes for idMensaje.
     */
    com.google.protobuf.ByteString
        getIdMensajeBytes();

    /**
     * <pre>
     * Tipo de mensaje
     * </pre>
     *
     * <code>string mensajeType = 2;</code>
     * @return The mensajeType.
     */
    java.lang.String getMensajeType();
    /**
     * <pre>
     * Tipo de mensaje
     * </pre>
     *
     * <code>string mensajeType = 2;</code>
     * @return The bytes for mensajeType.
     */
    com.google.protobuf.ByteString
        getMensajeTypeBytes();

    /**
     * <pre>
     * JSON serializado como string
     * </pre>
     *
     * <code>string mensajeJson = 3;</code>
     * @return The mensajeJson.
     */
    java.lang.String getMensajeJson();
    /**
     * <pre>
     * JSON serializado como string
     * </pre>
     *
     * <code>string mensajeJson = 3;</code>
     * @return The bytes for mensajeJson.
     */
    com.google.protobuf.ByteString
        getMensajeJsonBytes();

    /**
     * <pre>
     * Si es necesario se setea el idSector para definir destinatarios
     * </pre>
     *
     * <code>int32 idSector = 4;</code>
     * @return The idSector.
     */
    int getIdSector();

    /**
     * <pre>
     * Si es necesario se setea el idUsuario para definir destinatario.
     * </pre>
     *
     * <code>int32 idUsuario = 5;</code>
     * @return The idUsuario.
     */
    int getIdUsuario();

    /**
     * <pre>
     * milisegundos desde epoch
     * </pre>
     *
     * <code>int64 fechaEnvio = 6;</code>
     * @return The fechaEnvio.
     */
    long getFechaEnvio();
  }
  /**
   * <pre>
   * Mensaje para encapsular JSON con múltiples destinatarios
   * </pre>
   *
   * Protobuf type {@code coop.bancocredicoop.omnited.config.MensajeJSON}
   */
  public static final class MensajeJSON extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:coop.bancocredicoop.omnited.config.MensajeJSON)
      MensajeJSONOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MensajeJSON.newBuilder() to construct.
    private MensajeJSON(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MensajeJSON() {
      idMensaje_ = "";
      mensajeType_ = "";
      mensajeJson_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MensajeJSON();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return coop.bancocredicoop.omnited.config.MessageOut.internal_static_coop_bancocredicoop_omnited_config_MensajeJSON_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return coop.bancocredicoop.omnited.config.MessageOut.internal_static_coop_bancocredicoop_omnited_config_MensajeJSON_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              coop.bancocredicoop.omnited.config.MessageOut.MensajeJSON.class, coop.bancocredicoop.omnited.config.MessageOut.MensajeJSON.Builder.class);
    }

    public static final int IDMENSAJE_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object idMensaje_ = "";
    /**
     * <pre>
     * Un campo de tipo string con el identificador único
     * </pre>
     *
     * <code>string idMensaje = 1;</code>
     * @return The idMensaje.
     */
    @java.lang.Override
    public java.lang.String getIdMensaje() {
      java.lang.Object ref = idMensaje_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        idMensaje_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Un campo de tipo string con el identificador único
     * </pre>
     *
     * <code>string idMensaje = 1;</code>
     * @return The bytes for idMensaje.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdMensajeBytes() {
      java.lang.Object ref = idMensaje_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        idMensaje_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MENSAJETYPE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object mensajeType_ = "";
    /**
     * <pre>
     * Tipo de mensaje
     * </pre>
     *
     * <code>string mensajeType = 2;</code>
     * @return The mensajeType.
     */
    @java.lang.Override
    public java.lang.String getMensajeType() {
      java.lang.Object ref = mensajeType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mensajeType_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Tipo de mensaje
     * </pre>
     *
     * <code>string mensajeType = 2;</code>
     * @return The bytes for mensajeType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMensajeTypeBytes() {
      java.lang.Object ref = mensajeType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mensajeType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MENSAJEJSON_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object mensajeJson_ = "";
    /**
     * <pre>
     * JSON serializado como string
     * </pre>
     *
     * <code>string mensajeJson = 3;</code>
     * @return The mensajeJson.
     */
    @java.lang.Override
    public java.lang.String getMensajeJson() {
      java.lang.Object ref = mensajeJson_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mensajeJson_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * JSON serializado como string
     * </pre>
     *
     * <code>string mensajeJson = 3;</code>
     * @return The bytes for mensajeJson.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMensajeJsonBytes() {
      java.lang.Object ref = mensajeJson_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mensajeJson_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IDSECTOR_FIELD_NUMBER = 4;
    private int idSector_ = 0;
    /**
     * <pre>
     * Si es necesario se setea el idSector para definir destinatarios
     * </pre>
     *
     * <code>int32 idSector = 4;</code>
     * @return The idSector.
     */
    @java.lang.Override
    public int getIdSector() {
      return idSector_;
    }

    public static final int IDUSUARIO_FIELD_NUMBER = 5;
    private int idUsuario_ = 0;
    /**
     * <pre>
     * Si es necesario se setea el idUsuario para definir destinatario.
     * </pre>
     *
     * <code>int32 idUsuario = 5;</code>
     * @return The idUsuario.
     */
    @java.lang.Override
    public int getIdUsuario() {
      return idUsuario_;
    }

    public static final int FECHAENVIO_FIELD_NUMBER = 6;
    private long fechaEnvio_ = 0L;
    /**
     * <pre>
     * milisegundos desde epoch
     * </pre>
     *
     * <code>int64 fechaEnvio = 6;</code>
     * @return The fechaEnvio.
     */
    @java.lang.Override
    public long getFechaEnvio() {
      return fechaEnvio_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(idMensaje_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, idMensaje_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(mensajeType_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, mensajeType_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(mensajeJson_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, mensajeJson_);
      }
      if (idSector_ != 0) {
        output.writeInt32(4, idSector_);
      }
      if (idUsuario_ != 0) {
        output.writeInt32(5, idUsuario_);
      }
      if (fechaEnvio_ != 0L) {
        output.writeInt64(6, fechaEnvio_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(idMensaje_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, idMensaje_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(mensajeType_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, mensajeType_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(mensajeJson_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, mensajeJson_);
      }
      if (idSector_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, idSector_);
      }
      if (idUsuario_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, idUsuario_);
      }
      if (fechaEnvio_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, fechaEnvio_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof coop.bancocredicoop.omnited.config.MessageOut.MensajeJSON)) {
        return super.equals(obj);
      }
      coop.bancocredicoop.omnited.config.MessageOut.MensajeJSON other = (coop.bancocredicoop.omnited.config.MessageOut.MensajeJSON) obj;

      if (!getIdMensaje()
          .equals(other.getIdMensaje())) return false;
      if (!getMensajeType()
          .equals(other.getMensajeType())) return false;
      if (!getMensajeJson()
          .equals(other.getMensajeJson())) return false;
      if (getIdSector()
          != other.getIdSector()) return false;
      if (getIdUsuario()
          != other.getIdUsuario()) return false;
      if (getFechaEnvio()
          != other.getFechaEnvio()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + IDMENSAJE_FIELD_NUMBER;
      hash = (53 * hash) + getIdMensaje().hashCode();
      hash = (37 * hash) + MENSAJETYPE_FIELD_NUMBER;
      hash = (53 * hash) + getMensajeType().hashCode();
      hash = (37 * hash) + MENSAJEJSON_FIELD_NUMBER;
      hash = (53 * hash) + getMensajeJson().hashCode();
      hash = (37 * hash) + IDSECTOR_FIELD_NUMBER;
      hash = (53 * hash) + getIdSector();
      hash = (37 * hash) + IDUSUARIO_FIELD_NUMBER;
      hash = (53 * hash) + getIdUsuario();
      hash = (37 * hash) + FECHAENVIO_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getFechaEnvio());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static coop.bancocredicoop.omnited.config.MessageOut.MensajeJSON parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static coop.bancocredicoop.omnited.config.MessageOut.MensajeJSON parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static coop.bancocredicoop.omnited.config.MessageOut.MensajeJSON parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static coop.bancocredicoop.omnited.config.MessageOut.MensajeJSON parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static coop.bancocredicoop.omnited.config.MessageOut.MensajeJSON parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static coop.bancocredicoop.omnited.config.MessageOut.MensajeJSON parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static coop.bancocredicoop.omnited.config.MessageOut.MensajeJSON parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static coop.bancocredicoop.omnited.config.MessageOut.MensajeJSON parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static coop.bancocredicoop.omnited.config.MessageOut.MensajeJSON parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static coop.bancocredicoop.omnited.config.MessageOut.MensajeJSON parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static coop.bancocredicoop.omnited.config.MessageOut.MensajeJSON parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static coop.bancocredicoop.omnited.config.MessageOut.MensajeJSON parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(coop.bancocredicoop.omnited.config.MessageOut.MensajeJSON prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Mensaje para encapsular JSON con múltiples destinatarios
     * </pre>
     *
     * Protobuf type {@code coop.bancocredicoop.omnited.config.MensajeJSON}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:coop.bancocredicoop.omnited.config.MensajeJSON)
        coop.bancocredicoop.omnited.config.MessageOut.MensajeJSONOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return coop.bancocredicoop.omnited.config.MessageOut.internal_static_coop_bancocredicoop_omnited_config_MensajeJSON_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return coop.bancocredicoop.omnited.config.MessageOut.internal_static_coop_bancocredicoop_omnited_config_MensajeJSON_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                coop.bancocredicoop.omnited.config.MessageOut.MensajeJSON.class, coop.bancocredicoop.omnited.config.MessageOut.MensajeJSON.Builder.class);
      }

      // Construct using coop.bancocredicoop.omnited.config.MessageOut.MensajeJSON.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        idMensaje_ = "";
        mensajeType_ = "";
        mensajeJson_ = "";
        idSector_ = 0;
        idUsuario_ = 0;
        fechaEnvio_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return coop.bancocredicoop.omnited.config.MessageOut.internal_static_coop_bancocredicoop_omnited_config_MensajeJSON_descriptor;
      }

      @java.lang.Override
      public coop.bancocredicoop.omnited.config.MessageOut.MensajeJSON getDefaultInstanceForType() {
        return coop.bancocredicoop.omnited.config.MessageOut.MensajeJSON.getDefaultInstance();
      }

      @java.lang.Override
      public coop.bancocredicoop.omnited.config.MessageOut.MensajeJSON build() {
        coop.bancocredicoop.omnited.config.MessageOut.MensajeJSON result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public coop.bancocredicoop.omnited.config.MessageOut.MensajeJSON buildPartial() {
        coop.bancocredicoop.omnited.config.MessageOut.MensajeJSON result = new coop.bancocredicoop.omnited.config.MessageOut.MensajeJSON(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(coop.bancocredicoop.omnited.config.MessageOut.MensajeJSON result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.idMensaje_ = idMensaje_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.mensajeType_ = mensajeType_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.mensajeJson_ = mensajeJson_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.idSector_ = idSector_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.idUsuario_ = idUsuario_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.fechaEnvio_ = fechaEnvio_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof coop.bancocredicoop.omnited.config.MessageOut.MensajeJSON) {
          return mergeFrom((coop.bancocredicoop.omnited.config.MessageOut.MensajeJSON)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(coop.bancocredicoop.omnited.config.MessageOut.MensajeJSON other) {
        if (other == coop.bancocredicoop.omnited.config.MessageOut.MensajeJSON.getDefaultInstance()) return this;
        if (!other.getIdMensaje().isEmpty()) {
          idMensaje_ = other.idMensaje_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getMensajeType().isEmpty()) {
          mensajeType_ = other.mensajeType_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getMensajeJson().isEmpty()) {
          mensajeJson_ = other.mensajeJson_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.getIdSector() != 0) {
          setIdSector(other.getIdSector());
        }
        if (other.getIdUsuario() != 0) {
          setIdUsuario(other.getIdUsuario());
        }
        if (other.getFechaEnvio() != 0L) {
          setFechaEnvio(other.getFechaEnvio());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                idMensaje_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                mensajeType_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                mensajeJson_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 32: {
                idSector_ = input.readInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 40: {
                idUsuario_ = input.readInt32();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 48: {
                fechaEnvio_ = input.readInt64();
                bitField0_ |= 0x00000020;
                break;
              } // case 48
              default: {
                //if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                //}
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object idMensaje_ = "";
      /**
       * <pre>
       * Un campo de tipo string con el identificador único
       * </pre>
       *
       * <code>string idMensaje = 1;</code>
       * @return The idMensaje.
       */
      public java.lang.String getIdMensaje() {
        java.lang.Object ref = idMensaje_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          idMensaje_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Un campo de tipo string con el identificador único
       * </pre>
       *
       * <code>string idMensaje = 1;</code>
       * @return The bytes for idMensaje.
       */
      public com.google.protobuf.ByteString
          getIdMensajeBytes() {
        java.lang.Object ref = idMensaje_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          idMensaje_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Un campo de tipo string con el identificador único
       * </pre>
       *
       * <code>string idMensaje = 1;</code>
       * @param value The idMensaje to set.
       * @return This builder for chaining.
       */
      public Builder setIdMensaje(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        idMensaje_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Un campo de tipo string con el identificador único
       * </pre>
       *
       * <code>string idMensaje = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearIdMensaje() {
        idMensaje_ = getDefaultInstance().getIdMensaje();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Un campo de tipo string con el identificador único
       * </pre>
       *
       * <code>string idMensaje = 1;</code>
       * @param value The bytes for idMensaje to set.
       * @return This builder for chaining.
       */
      public Builder setIdMensajeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        idMensaje_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object mensajeType_ = "";
      /**
       * <pre>
       * Tipo de mensaje
       * </pre>
       *
       * <code>string mensajeType = 2;</code>
       * @return The mensajeType.
       */
      public java.lang.String getMensajeType() {
        java.lang.Object ref = mensajeType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          mensajeType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Tipo de mensaje
       * </pre>
       *
       * <code>string mensajeType = 2;</code>
       * @return The bytes for mensajeType.
       */
      public com.google.protobuf.ByteString
          getMensajeTypeBytes() {
        java.lang.Object ref = mensajeType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mensajeType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Tipo de mensaje
       * </pre>
       *
       * <code>string mensajeType = 2;</code>
       * @param value The mensajeType to set.
       * @return This builder for chaining.
       */
      public Builder setMensajeType(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        mensajeType_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Tipo de mensaje
       * </pre>
       *
       * <code>string mensajeType = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMensajeType() {
        mensajeType_ = getDefaultInstance().getMensajeType();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Tipo de mensaje
       * </pre>
       *
       * <code>string mensajeType = 2;</code>
       * @param value The bytes for mensajeType to set.
       * @return This builder for chaining.
       */
      public Builder setMensajeTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        mensajeType_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object mensajeJson_ = "";
      /**
       * <pre>
       * JSON serializado como string
       * </pre>
       *
       * <code>string mensajeJson = 3;</code>
       * @return The mensajeJson.
       */
      public java.lang.String getMensajeJson() {
        java.lang.Object ref = mensajeJson_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          mensajeJson_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * JSON serializado como string
       * </pre>
       *
       * <code>string mensajeJson = 3;</code>
       * @return The bytes for mensajeJson.
       */
      public com.google.protobuf.ByteString
          getMensajeJsonBytes() {
        java.lang.Object ref = mensajeJson_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mensajeJson_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * JSON serializado como string
       * </pre>
       *
       * <code>string mensajeJson = 3;</code>
       * @param value The mensajeJson to set.
       * @return This builder for chaining.
       */
      public Builder setMensajeJson(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        mensajeJson_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * JSON serializado como string
       * </pre>
       *
       * <code>string mensajeJson = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMensajeJson() {
        mensajeJson_ = getDefaultInstance().getMensajeJson();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * JSON serializado como string
       * </pre>
       *
       * <code>string mensajeJson = 3;</code>
       * @param value The bytes for mensajeJson to set.
       * @return This builder for chaining.
       */
      public Builder setMensajeJsonBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        mensajeJson_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private int idSector_ ;
      /**
       * <pre>
       * Si es necesario se setea el idSector para definir destinatarios
       * </pre>
       *
       * <code>int32 idSector = 4;</code>
       * @return The idSector.
       */
      @java.lang.Override
      public int getIdSector() {
        return idSector_;
      }
      /**
       * <pre>
       * Si es necesario se setea el idSector para definir destinatarios
       * </pre>
       *
       * <code>int32 idSector = 4;</code>
       * @param value The idSector to set.
       * @return This builder for chaining.
       */
      public Builder setIdSector(int value) {
        
        idSector_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Si es necesario se setea el idSector para definir destinatarios
       * </pre>
       *
       * <code>int32 idSector = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearIdSector() {
        bitField0_ = (bitField0_ & ~0x00000008);
        idSector_ = 0;
        onChanged();
        return this;
      }

      private int idUsuario_ ;
      /**
       * <pre>
       * Si es necesario se setea el idUsuario para definir destinatario.
       * </pre>
       *
       * <code>int32 idUsuario = 5;</code>
       * @return The idUsuario.
       */
      @java.lang.Override
      public int getIdUsuario() {
        return idUsuario_;
      }
      /**
       * <pre>
       * Si es necesario se setea el idUsuario para definir destinatario.
       * </pre>
       *
       * <code>int32 idUsuario = 5;</code>
       * @param value The idUsuario to set.
       * @return This builder for chaining.
       */
      public Builder setIdUsuario(int value) {
        
        idUsuario_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Si es necesario se setea el idUsuario para definir destinatario.
       * </pre>
       *
       * <code>int32 idUsuario = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearIdUsuario() {
        bitField0_ = (bitField0_ & ~0x00000010);
        idUsuario_ = 0;
        onChanged();
        return this;
      }

      private long fechaEnvio_ ;
      /**
       * <pre>
       * milisegundos desde epoch
       * </pre>
       *
       * <code>int64 fechaEnvio = 6;</code>
       * @return The fechaEnvio.
       */
      @java.lang.Override
      public long getFechaEnvio() {
        return fechaEnvio_;
      }
      /**
       * <pre>
       * milisegundos desde epoch
       * </pre>
       *
       * <code>int64 fechaEnvio = 6;</code>
       * @param value The fechaEnvio to set.
       * @return This builder for chaining.
       */
      public Builder setFechaEnvio(long value) {
        
        fechaEnvio_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * milisegundos desde epoch
       * </pre>
       *
       * <code>int64 fechaEnvio = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearFechaEnvio() {
        bitField0_ = (bitField0_ & ~0x00000020);
        fechaEnvio_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:coop.bancocredicoop.omnited.config.MensajeJSON)
    }

    // @@protoc_insertion_point(class_scope:coop.bancocredicoop.omnited.config.MensajeJSON)
    private static final coop.bancocredicoop.omnited.config.MessageOut.MensajeJSON DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new coop.bancocredicoop.omnited.config.MessageOut.MensajeJSON();
    }

    public static coop.bancocredicoop.omnited.config.MessageOut.MensajeJSON getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MensajeJSON>
        PARSER = new com.google.protobuf.AbstractParser<MensajeJSON>() {
      @java.lang.Override
      public MensajeJSON parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MensajeJSON> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MensajeJSON> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public coop.bancocredicoop.omnited.config.MessageOut.MensajeJSON getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coop_bancocredicoop_omnited_config_MensajeJSON_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coop_bancocredicoop_omnited_config_MensajeJSON_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020messageOut.proto\022\"coop.bancocredicoop." +
      "omnited.config\"\203\001\n\013MensajeJSON\022\021\n\tidMens" +
      "aje\030\001 \001(\t\022\023\n\013mensajeType\030\002 \001(\t\022\023\n\013mensaj" +
      "eJson\030\003 \001(\t\022\020\n\010idSector\030\004 \001(\005\022\021\n\tidUsuar" +
      "io\030\005 \001(\005\022\022\n\nfechaEnvio\030\006 \001(\003b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_coop_bancocredicoop_omnited_config_MensajeJSON_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_coop_bancocredicoop_omnited_config_MensajeJSON_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coop_bancocredicoop_omnited_config_MensajeJSON_descriptor,
        new java.lang.String[] { "IdMensaje", "MensajeType", "MensajeJson", "IdSector", "IdUsuario", "FechaEnvio", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
